### ISSUE TITLE
Consola v4 roadmap

### ISSUE THREAD

**Issue by pi0** [unjs/consola#335]
### Describe the feature

- [ ] Animated spinner (https://github.com/unjs/consola/pull/334)
- [ ] Remove timestamp from righthand
- [ ] ESM-only dist
- [ ] Remove legacy core aliases / reexports
- [ ] Move tags to the left to avoid whitespace paddings

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by hirasso** [comment]
Any plans to add color support for logging in browsers?

**Comment by onmax** [comment]
Hey, what do you think about #317?

**Comment by maxdzin** [comment]
Hi @pi0,
I wondering about the status of this project, and, in particular, v4. Is it supposed to be continued?
Currently, there are many opened PRs and it looks kinda abandoned.
Or maybe there are better alternatives?
